import { createApp } from 'vue';
import { VueMasonryPlugin } from "vue-masonry/src/masonry.plugin.js";
import { createHead, Head } from '@vueuse/head';
import bounce_ui from "bounce-ui-vue";
import Popper from "vue3-popper";
import { Skeletor } from 'vue-skeletor';
import Notifications from '@kyvg/vue3-notification';
import App from './App.vue';
import VLazyImage from "v-lazy-image";
import FileUpload from "./components/FileUpload/FileUpload.vue";
import router from './router';
import './registerServiceWorker';
import 'vue-skeletor/dist/vue-skeletor.css';
const app = createApp(App);
const head = createHead();
app.use(head);
app.use(bounce_ui);
app.use(router);
app.use(VueMasonryPlugin);
app.use(Notifications);
app.component("VLazyImage", VLazyImage);
app.component("FileUpload", FileUpload);
app.component("Head", Head);
app.component(Skeletor.name, Skeletor);
app.component("Popper", Popper);
app.mount('#app');